name: beyond_helpers
description: Utilities for implementing beyond architecture patterns
version: 1.0.0+1
homepage: https://github.com/MisterJimson/beyond

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  mobx: ^1.2.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  flutter_mobx: ^1.1.0+1
  flutter_test:
    sdk: flutter

flutter: